/*
 * This file is generated by jOOQ.
 */
package com.ardikapras.simplepos.domain.model.schema.tables.pojos


import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Entity
@Table(
    name = "customers",
    schema = "public"
)
data class CustomersPojo(
    @get:Id
    @get:GeneratedValue(strategy = GenerationType.IDENTITY)
    @get:Column(name = "customer_id", nullable = false, precision = 32)
    val customerId: Int? = null,
    @get:Column(name = "first_name", nullable = false, length = 50)
    @get:NotNull
    @get:Size(max = 50)
    val firstName: String? = null,
    @get:Column(name = "last_name", nullable = false, length = 50)
    @get:NotNull
    @get:Size(max = 50)
    val lastName: String? = null,
    @get:Column(name = "email", length = 100)
    @get:Size(max = 100)
    val email: String? = null,
    @get:Column(name = "phone", length = 20)
    @get:Size(max = 20)
    val phone: String? = null,
    @get:Column(name = "address")
    val address: String? = null,
    @get:Column(name = "created_at", precision = 6)
    val createdAt: LocalDateTime? = null,
    @get:Column(name = "updated_at", precision = 6)
    val updatedAt: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("CustomersPojo (")

        sb.append(customerId)
        sb.append(", ").append(firstName)
        sb.append(", ").append(lastName)
        sb.append(", ").append(email)
        sb.append(", ").append(phone)
        sb.append(", ").append(address)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
