/*
 * This file is generated by jOOQ.
 */
package com.ardikapras.simplepos.domain.model.schema.tables.pojos


import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import jakarta.validation.constraints.NotNull

import java.io.Serializable
import java.math.BigDecimal
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Entity
@Table(
    name = "orders",
    schema = "public"
)
data class OrdersPojo(
    @get:Id
    @get:GeneratedValue(strategy = GenerationType.IDENTITY)
    @get:Column(name = "order_id", nullable = false, precision = 32)
    val orderId: Int? = null,
    @get:Column(name = "user_id", precision = 32)
    val userId: Int? = null,
    @get:Column(name = "customer_id", precision = 32)
    val customerId: Int? = null,
    @get:Column(name = "order_date", precision = 6)
    val orderDate: OffsetDateTime? = null,
    @get:Column(name = "total_amount", nullable = false, precision = 10, scale = 2)
    @get:NotNull
    val totalAmount: BigDecimal? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("OrdersPojo (")

        sb.append(orderId)
        sb.append(", ").append(userId)
        sb.append(", ").append(customerId)
        sb.append(", ").append(orderDate)
        sb.append(", ").append(totalAmount)

        sb.append(")")
        return sb.toString()
    }
}
