/*
 * This file is generated by jOOQ.
 */
package com.ardikapras.simplepos.domain.model.schema.tables.pojos


import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable
import java.math.BigDecimal
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Entity
@Table(
    name = "products",
    schema = "public"
)
data class ProductsPojo(
    @get:Id
    @get:GeneratedValue(strategy = GenerationType.IDENTITY)
    @get:Column(name = "product_id", nullable = false, precision = 64)
    val productId: Long? = null,
    @get:Column(name = "name", nullable = false, length = 100)
    @get:NotNull
    @get:Size(max = 100)
    val name: String? = null,
    @get:Column(name = "description")
    val description: String? = null,
    @get:Column(name = "price", nullable = false, precision = 38, scale = 2)
    @get:NotNull
    val price: BigDecimal? = null,
    @get:Column(name = "quantity", nullable = false, precision = 32)
    @get:NotNull
    val quantity: Int? = null,
    @get:Column(name = "created_at", precision = 6)
    val createdAt: LocalDateTime? = null,
    @get:Column(name = "updated_at", precision = 6)
    val updatedAt: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("ProductsPojo (")

        sb.append(productId)
        sb.append(", ").append(name)
        sb.append(", ").append(description)
        sb.append(", ").append(price)
        sb.append(", ").append(quantity)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(updatedAt)

        sb.append(")")
        return sb.toString()
    }
}
