/*
 * This file is generated by jOOQ.
 */
package com.ardikapras.simplepos.domain.model.schema.tables.pojos


import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size

import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
@Entity
@Table(
    name = "users",
    schema = "public"
)
data class UsersPojo(
    @get:Id
    @get:GeneratedValue(strategy = GenerationType.IDENTITY)
    @get:Column(name = "user_id", nullable = false, precision = 32)
    val userId: Int? = null,
    @get:Column(name = "username", nullable = false, length = 50)
    @get:NotNull
    @get:Size(max = 50)
    val username: String? = null,
    @get:Column(name = "password", nullable = false, length = 255)
    @get:NotNull
    @get:Size(max = 255)
    val password: String? = null,
    @get:Column(name = "role", nullable = false, length = 20)
    @get:NotNull
    @get:Size(max = 20)
    val role: String? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("UsersPojo (")

        sb.append(userId)
        sb.append(", ").append(username)
        sb.append(", ").append(password)
        sb.append(", ").append(role)

        sb.append(")")
        return sb.toString()
    }
}
