/*
 * This file is generated by jOOQ.
 */
package com.ardikapras.simplepos.domain.model.schema.tables.references


import com.ardikapras.simplepos.domain.model.schema.tables.Customers
import com.ardikapras.simplepos.domain.model.schema.tables.OrderItems
import com.ardikapras.simplepos.domain.model.schema.tables.Orders
import com.ardikapras.simplepos.domain.model.schema.tables.Products
import com.ardikapras.simplepos.domain.model.schema.tables.Users



/**
 * The table <code>public.customers</code>.
 */
val CUSTOMERS: Customers = Customers.CUSTOMERS

/**
 * The table <code>public.order_items</code>.
 */
val ORDER_ITEMS: OrderItems = OrderItems.ORDER_ITEMS

/**
 * The table <code>public.orders</code>.
 */
val ORDERS: Orders = Orders.ORDERS

/**
 * The table <code>public.products</code>.
 */
val PRODUCTS: Products = Products.PRODUCTS

/**
 * The table <code>public.users</code>.
 */
val USERS: Users = Users.USERS
