version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: simple-pos
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgresql-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
