/*
 * This file is generated by jOOQ.
 */
package com.ardikapras.simplepos.domain.model.schema.tables


import com.ardikapras.simplepos.domain.model.schema.Public
import com.ardikapras.simplepos.domain.model.schema.keys.PRODUCTS_PKEY
import com.ardikapras.simplepos.domain.model.schema.tables.records.ProductsRecord

import java.math.BigDecimal
import java.time.LocalDateTime
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row7
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Products(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ProductsRecord>?,
    aliased: Table<ProductsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ProductsRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.products</code>
         */
        val PRODUCTS: Products = Products()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ProductsRecord> = ProductsRecord::class.java

    /**
     * The column <code>public.products.product_id</code>.
     */
    val PRODUCT_ID: TableField<ProductsRecord, Long?> = createField(DSL.name("product_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.products.name</code>.
     */
    val NAME: TableField<ProductsRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.products.description</code>.
     */
    val DESCRIPTION: TableField<ProductsRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.products.price</code>.
     */
    val PRICE: TableField<ProductsRecord, BigDecimal?> = createField(DSL.name("price"), SQLDataType.NUMERIC(38, 2).nullable(false), this, "")

    /**
     * The column <code>public.products.quantity</code>.
     */
    val QUANTITY: TableField<ProductsRecord, Int?> = createField(DSL.name("quantity"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.products.created_at</code>.
     */
    val CREATED_AT: TableField<ProductsRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.products.updated_at</code>.
     */
    val UPDATED_AT: TableField<ProductsRecord, LocalDateTime?> = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<ProductsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ProductsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.products</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.products</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.products</code> table reference
     */
    constructor(): this(DSL.name("products"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ProductsRecord>): this(Internal.createPathAlias(child, key), child, key, PRODUCTS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<ProductsRecord, Long?> = super.getIdentity() as Identity<ProductsRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<ProductsRecord> = PRODUCTS_PKEY
    override fun `as`(alias: String): Products = Products(DSL.name(alias), this)
    override fun `as`(alias: Name): Products = Products(alias, this)
    override fun `as`(alias: Table<*>): Products = Products(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Products = Products(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Products = Products(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Products = Products(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row7<Long?, String?, String?, BigDecimal?, Int?, LocalDateTime?, LocalDateTime?> = super.fieldsRow() as Row7<Long?, String?, String?, BigDecimal?, Int?, LocalDateTime?, LocalDateTime?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, String?, String?, BigDecimal?, Int?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, String?, String?, BigDecimal?, Int?, LocalDateTime?, LocalDateTime?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
