/*
 * This file is generated by jOOQ.
 */
package com.ardikapras.simplepos.domain.model.schema.keys


import com.ardikapras.simplepos.domain.model.schema.tables.Customers
import com.ardikapras.simplepos.domain.model.schema.tables.OrderItems
import com.ardikapras.simplepos.domain.model.schema.tables.Orders
import com.ardikapras.simplepos.domain.model.schema.tables.Products
import com.ardikapras.simplepos.domain.model.schema.tables.Users
import com.ardikapras.simplepos.domain.model.schema.tables.records.CustomersRecord
import com.ardikapras.simplepos.domain.model.schema.tables.records.OrderItemsRecord
import com.ardikapras.simplepos.domain.model.schema.tables.records.OrdersRecord
import com.ardikapras.simplepos.domain.model.schema.tables.records.ProductsRecord
import com.ardikapras.simplepos.domain.model.schema.tables.records.UsersRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val CUSTOMERS_PKEY: UniqueKey<CustomersRecord> = Internal.createUniqueKey(Customers.CUSTOMERS, DSL.name("customers_pkey"), arrayOf(Customers.CUSTOMERS.CUSTOMER_ID), true)
val ORDER_ITEMS_PKEY: UniqueKey<OrderItemsRecord> = Internal.createUniqueKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_pkey"), arrayOf(OrderItems.ORDER_ITEMS.ORDER_ITEM_ID), true)
val ORDERS_PKEY: UniqueKey<OrdersRecord> = Internal.createUniqueKey(Orders.ORDERS, DSL.name("orders_pkey"), arrayOf(Orders.ORDERS.ORDER_ID), true)
val PRODUCTS_PKEY: UniqueKey<ProductsRecord> = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("products_pkey"), arrayOf(Products.PRODUCTS.PRODUCT_ID), true)
val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), arrayOf(Users.USERS.USER_ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val ORDER_ITEMS__ORDER_ITEMS_ORDER_ID_FKEY: ForeignKey<OrderItemsRecord, OrdersRecord> = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_order_id_fkey"), arrayOf(OrderItems.ORDER_ITEMS.ORDER_ID), com.ardikapras.simplepos.domain.model.schema.keys.ORDERS_PKEY, arrayOf(Orders.ORDERS.ORDER_ID), true)
val ORDER_ITEMS__ORDER_ITEMS_PRODUCT_ID_FKEY: ForeignKey<OrderItemsRecord, ProductsRecord> = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_product_id_fkey"), arrayOf(OrderItems.ORDER_ITEMS.PRODUCT_ID), com.ardikapras.simplepos.domain.model.schema.keys.PRODUCTS_PKEY, arrayOf(Products.PRODUCTS.PRODUCT_ID), true)
val ORDERS__ORDERS_CUSTOMER_ID_FKEY: ForeignKey<OrdersRecord, CustomersRecord> = Internal.createForeignKey(Orders.ORDERS, DSL.name("orders_customer_id_fkey"), arrayOf(Orders.ORDERS.CUSTOMER_ID), com.ardikapras.simplepos.domain.model.schema.keys.CUSTOMERS_PKEY, arrayOf(Customers.CUSTOMERS.CUSTOMER_ID), true)
val ORDERS__ORDERS_USER_ID_FKEY: ForeignKey<OrdersRecord, UsersRecord> = Internal.createForeignKey(Orders.ORDERS, DSL.name("orders_user_id_fkey"), arrayOf(Orders.ORDERS.USER_ID), com.ardikapras.simplepos.domain.model.schema.keys.USERS_PKEY, arrayOf(Users.USERS.USER_ID), true)
